bashni/urls.py
from django.contrib import admin
from django.urls import path, include

import bashni.views
from bashni import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.contrib.sitemaps.views import sitemap

from main import views as main_views
from property import views as pr_views

sitemaps = {
    'index': main_views.IndexViewSitemap,
    'static': main_views.StaticViewSitemap,
    'news_slug': main_views.NewsSlugVladivostokSitemapView,
    'news': main_views.NewsSitemapView,
    'property': pr_views.PropertySitemapView,
    'property_detail': pr_views.PropertyDetailSitemapView,
    'flats_detail': pr_views.FlatsDetailSitemapView
}

handler404 = bashni.views.page_not_found_view
handler500 = bashni.views.custom_error_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('property/', include('property.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('lk/', include('cabinet.urls', namespace='cabinet')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

cabinet/urls.py
from django.urls import path
from cabinet import views

app_name = 'cabinet'


urlpatterns = [
    path('<pk>/main/', views.MainView.as_view(), name='main'),
    path('<pk>/profile/', views.UserVew.as_view(), name='profile'),
    path('<pk>/subscriptions/', views.SubscriptionsView.as_view(), name='subscriptions'),
    path('<pk>/documents/', views.DocsView.as_view(), name='docs'),
    path('<pk>/reservations/', views.ReserveView.as_view(), name='reserve'),
    path('<pk>/loan/', views.LoanView.as_view(), name='loan'),
    path('<pk>/compare/', views.CompareView.as_view(), name='compare'),
]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='main'),
    path('news/', views.NewsListView.as_view(), name='news'),
    path('news/<pk>/', views.NewsDetailList.as_view(), name='news_detail'),
    path('news_slug/<tag>/', views.NewsSlugView.as_view(), name='news_slug'),
    path('loan/', views.LoanPageView.as_view(), name='loan'),
    path('repair/', views.RepairPageView.as_view(), name='repair'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('favorites/', views.FavoritesView.as_view(), name='favorites'),
    path('events/', views.EventsView.as_view(), name='events'),
    path('events/<pk>/', views.EventsDetailView.as_view(), name='events_detail'),
    path('policy/', views.PolicyView.as_view(), name='policy'),
    path('news_popular/', views.PopularNewsListView.as_view(), name='news_popular'),
    path('person_data_treatment/', views.PersonDataView.as_view(), name='person_data'),
]

cabinet/models.py
from django.db import models
from django.contrib.auth.models import User

from property.models import Property, Flats


class FavoritesProperty(models.Model):
    property_pk = models.ForeignKey(Property, on_delete=models.CASCADE, verbose_name="избранный ЖК")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="пользователь",
                             related_name="favorite_properties")

    class Meta:
        verbose_name_plural = "Избранные новостройки"


class FavoritesFlats(models.Model):
    property_pk = models.ForeignKey(Flats, on_delete=models.CASCADE, verbose_name="избранная квартира")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="пользователь", related_name="favorite_flats")

    class Meta:
        verbose_name_plural = "Избранные квартиры"

property/models.py
from django.db import models
from django.contrib.auth.models import User

from PIL import Image

from ckeditor_uploader.fields import RichTextUploadingField
from slugify import slugify


def resize_image(elem):
    org_img = Image.open(elem.path)
    width, height = org_img.size
    if width > 900:
        width_ratio = round(900 / width * 100)
        org_img.save(elem.path, quality=width_ratio)


class City(models.Model):
    city_name = models.CharField(verbose_name='город', max_length=32)
    city_slug = models.SlugField(verbose_name='поле url')
    city_code = models.PositiveSmallIntegerField(verbose_name='код города')

    class Meta:
        verbose_name_plural = 'Города'

    def __str__(self):
        return self.city_name


class Facilities(models.Model):
    name = models.CharField(verbose_name='возможности', max_length=128)
    vector = models.TextField(verbose_name='вектор рисунка', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'инфраструктура ЖК'


class RatingStar(models.Model):
    value = models.PositiveSmallIntegerField(verbose_name='значение')

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name_plural = 'Звезды рейтинга' 
        ordering = ['-value']


def path_to_property(instance, filename):
    return f'property/{instance.name}/{filename}'


class Property(models.Model):
    STAGE_CHOICES = (
        ('b', 'строится'),
        ('p', 'сдан'),
        ('d', 'долгострой'),
    )
    key_words = models.CharField(max_length=256, verbose_name='ключевые слова для мета тэгов', blank=True)
    description = models.CharField(max_length=300, verbose_name='описание для мета тэгов', blank=True)
    name = models.CharField(max_length=128, verbose_name='Название ЖК', unique=True)
    slug = models.SlugField(verbose_name='поле url', max_length=128)
    build_stage = models.CharField(max_length=15, verbose_name='Стадия строительства', choices=STAGE_CHOICES, default='b')
    short_desc = RichTextUploadingField(verbose_name='Краткое описание', blank=True)
    territory_desc = RichTextUploadingField(verbose_name='Благоустройство', blank=True)
    infr_desc = RichTextUploadingField(verbose_name='Инфраструктура', blank=True)
    work_desc = RichTextUploadingField(verbose_name='Перечень работ', blank=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='Для города', related_name='prorerty')
    district = models.CharField(verbose_name='район', max_length=64, blank=True)
    buid_video = models.URLField(verbose_name='ссылка на видеонаблюдение', max_length=200, blank=True, null=True)
    gen_plan = models.ImageField(verbose_name='ген план', upload_to=path_to_property, blank=True, null=True)
    zhk_img = models.ImageField(verbose_name='картинка записаться на просмотр', upload_to=path_to_property, blank=True, null=True)
    facilities = models.ManyToManyField(Facilities, verbose_name='инфраструктура')
    video = models.URLField(verbose_name='видеопрезентация', max_length=200, blank=True, null=True,
        help_text='в конце адреса ?autoplay=1&mute=1, например: https://www.youtube.com/embed/hdi6vkQx?autoplay=1&mute=1')
    has_scraper = models.BooleanField(verbose_name='есть скрапер', default=False)
    is_active = models.BooleanField(verbose_name='активный', default=True)
    mid_rating = models.DecimalField(verbose_name='средний рейтинг новостройки', max_digits=2, decimal_places=1, default=0.0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'ЖК комплексы'
        ordering = ['name']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, ok='_', only_ascii=True)
        super(Property, self).save(*args, **kwargs)
        if self.gen_plan:
            super().save(*args, **kwargs)
            resize_image(self.gen_plan)
        if self.zhk_img:
            super().save(*args, **kwargs)
            resize_image(self.zhk_img)
       

class Rating(models.Model):
    ip = models.CharField(verbose_name='ip адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='звезда')
    property = models.ForeignKey(Property, on_delete=models.CASCADE, verbose_name='ЖК', related_name='rate')

    def get_rating(self):
        ratings = Rating.objects.filter(property=self.property)
        rate_sum = 0
        try:
            for item in ratings:
                rate_sum += item.star.value
            return round(rate_sum/len(ratings), 1)
        except Exception:
            return 0.0

    class Meta:
        verbose_name_plural = 'Рейтинг'


class PropertyTestimonials(models.Model):
    date = models.DateField(verbose_name='дата публикации', auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    testimonial = models.TextField(verbose_name='отзыв', max_length=512)
    fk_property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='testimonials')

    def __str__(self):
        return f'{self.date} {self.testimonial}'

    class Meta:
        verbose_name_plural = 'Отзывы о ЖК'


def img_path_small(instance, filename):
    return f'property/{instance.get_build_stage_display()}/{instance.id}/{filename}'


class Buildings(models.Model):
    STAGE_CHOICES = (
        ('b', 'строится'),
        ('p', 'сдан'),
        ('d', 'долгострой'),
    )
    key_words = models.CharField(max_length=256, verbose_name='ключевые слова для мета тэгов', blank=True)
    description = models.CharField(max_length=300, verbose_name='описание для мета тэгов', blank=True)
    fk_property = models.ForeignKey(Property, on_delete=models.CASCADE, verbose_name='ЖК')
    num_dom = models.CharField(max_length=64, verbose_name='номер строения/название дома')
    start_date = models.PositiveIntegerField(verbose_name='год начала строительства', blank=True, null=True)
    build_stage = models.CharField(max_length=15, verbose_name='Стадия строительства', choices=STAGE_CHOICES, default='b')
    addr = models.CharField(max_length=256, verbose_name='Адрес')
    small_img = models.ImageField(upload_to=img_path_small, verbose_name='уменьшенное фото')
    main_contractor = models.CharField(max_length=64, verbose_name='Застройщик')
    building_company = models.CharField(max_length=128, verbose_name='Подрядчик', blank=True)
    pr_declaration = models.CharField(max_length=128, verbose_name='Проектная декларация')
    pr_decl_link = models.URLField(verbose_name='Ссылка на проектную декларацию')
    operation_term = models.CharField(max_length=32, verbose_name='Ввод в эксплуатацию')
    send_keys = models.DateField(verbose_name='Выдача ключей', blank=True, null=True)
    middle_price = models.PositiveIntegerField(verbose_name='Средняя цена за 1 м2', blank=True, null=True)
    property_class = models.CharField(max_length=32, verbose_name='Класс недвижимости')
    wall = models.CharField(max_length=32, verbose_name='Материал стен')
    decoration = models.CharField(max_length=32, verbose_name='Тип отделки')
    free_planning = models.CharField(max_length=20, verbose_name='Свободная планировка')
    floors = models.PositiveSmallIntegerField(verbose_name='Количество этажей')
    q_flats = models.PositiveSmallIntegerField(verbose_name='Количество квартир')
    living_sq = models.PositiveIntegerField(verbose_name='Жилая площадь')
    ceil_height = models.CharField(max_length=15, verbose_name='Высота потолков')
    sales_flats = models.CharField(verbose_name='распроданность квартир', max_length=32, blank=True)
    sales_not_living = models.CharField(verbose_name='распроданность нежилых помещений', max_length=32, blank=True)
    sales_parking = models.CharField(verbose_name='распроданность машиномест', max_length=32, blank=True)
    is_active = models.BooleanField(verbose_name='активный', default=True)

    class Meta:
        verbose_name_plural = 'Объекты недвижимости'
        ordering = ['middle_price', 'operation_term', 'num_dom']

    def __str__(self):
        return self.num_dom


def img_path_photo(instance, filename):
    return f'property/{instance.fk_building.get_build_stage_display()}/{instance.fk_building.id}/{filename}'


class MainPhotos(models.Model):
    main_img = models.ImageField(upload_to=img_path_photo, verbose_name='фото')
    fk_building = models.ForeignKey(Buildings, on_delete=models.CASCADE, verbose_name='для объекта',
                                    related_name='main_photos')

    class Meta:
        verbose_name_plural = 'Основные фото'


def img_path_build(instance, filename):
    return f'property/{instance.fk_month.fk_building.get_build_stage_display()}/{instance.fk_month.fk_building.id}/building/{instance.fk_month.build_month}/{filename}'


class BuildMonths(models.Model):
    build_month = models.CharField(max_length=20, verbose_name='Месяц строительства')
    fk_building = models.ForeignKey(Buildings, on_delete=models.CASCADE, verbose_name='для объекта',
                                    related_name='build_months')
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        verbose_name_plural = 'Фото объектов по месяцам стр-ва'


class BuildingPhotos(models.Model):
    build_img = models.ImageField(upload_to=img_path_build, blank=True, null=True)
    fk_month = models.ForeignKey(BuildMonths, on_delete=models.CASCADE, verbose_name='месяц',
                                 related_name='build_photos')

    class Meta:
        verbose_name_plural = 'Фото строительства'


class ObjectDocuments(models.Model):
    doc_name = models.CharField(max_length=128, verbose_name='Тип документа')
    doc_date = models.DateTimeField(verbose_name='Дата размещения')
    doc_link = models.URLField(verbose_name='ссылка на документ')
    fk_object = models.ForeignKey(Buildings, on_delete=models.CASCADE, related_name='documents', verbose_name='для объекта')

    def __str__(self):
        return self.doc_name

    class Meta:

main/forms.py
from django import forms

from main.models import NewsComment


class NewsCommentForm(forms.ModelForm):
    class Meta:
        model = NewsComment
        fields = ['comment_text']

    def __init__(self, *args, **kwargs):
        super(NewsCommentForm, self).__init__(*args, **kwargs)
        self.fields['comment_text'] = forms.CharField(max_length=512, label='текст комментария',
                                                      widget=forms.Textarea(attrs={'rows': 5}), required=False)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

cabinet/templates/cabinet/docs.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Документы{% endblock title %}

{% block content %}
<div class="container px-sm-0 my-5">
    <div class="row">
        <div class="col-12 col-sm-4 col-xl-3 mb-5 left-menu">
            {% include 'cabinet/include/left-menu.html' %}
        </div>
        <div class="col-12 col-sm-8 col-xl-9 pl-sm-5">
            <h1 class="gray mb-5 pb-3" style="border-bottom: 1px solid rgba(0, 0, 0, 0.3)">Документы</h1>
            <p class="ml-5 h4 gray" style="margin-top: 5rem;">Пока здесь пусто...</p>
        </div>
    </div>
</div>
{% endblock content %}

cabinet/templates/cabinet/ipoteka.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Ипотека{% endblock title %}

{% block content %}
<div class="container px-sm-0 my-5">
    <div class="row">
        <div class="col-12 col-sm-4 col-xl-3 mb-5 left-menu">
            {% include 'cabinet/include/left-menu.html' %}
        </div>
        <div class="col-12 col-sm-8 col-xl-9 pl-sm-5">
            <h1 class="gray mb-5 pb-3" style="border-bottom: 1px solid rgba(0, 0, 0, 0.3)">Ипотека</h1>
            <ul class="nav type_object mb-4 pb-4" style="border-bottom: none;">
                <li value="bank_requests" class="active gray mr-3">Мои заявки</li>
                <li value="bank_conform" class="gray mr-3">Одобрения банков</li>
            </ul>
            <div class="block-6">
                <h4 class="mt-5 gray">Пока здесь пусто...</h4>
                <h4 class="mt-3 mb-5 gray">Вы можете оставить <a class="a_fav" href="#">заявку онлайн</a></h4>
            </div>
            <div class="block-7">
                <h4 class="mt-5 mb-5 gray">Пока здесь пусто...</h4>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

cabinet/templates/cabinet/letter.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Подписки{% endblock title %}

{% block content %}
<div class="container px-sm-0 my-5">
    <div class="row">
        <div class="col-12 col-sm-4 col-xl-3 mb-5 left-menu">
            {% include 'cabinet/include/left-menu.html' %}
        </div>
        <div class="col-12 col-sm-8 col-xl-9 pl-sm-5">
            <h1 class="gray mb-5 pb-3" style="border-bottom: 1px solid rgba(0, 0, 0, 0.3)">Подписки</h1>
            <p class="ml-5 h4 gray" style="margin-top: 5rem;">Пока здесь пусто...</p>
        </div>
    </div>
</div>
{% endblock content %}

cabinet/templates/cabinet/main.html
{% extends 'main/base.html' %}
{% load static %}
{% load view_price %}

{% block title %}Избранное{% endblock title %}

{% block content %}
<div class="container px-sm-0 my-5">
    <div class="row">
        <div class="col-12 col-sm-4 col-xl-3 mb-5 left-menu">
            {% include 'cabinet/include/left-menu.html' %}
        </div>
        <div class="col-12 col-sm-8 col-xl-9 pl-sm-5">
            <h1 class="gray mb-5 pb-3" style="border-bottom: 1px solid rgba(0, 0, 0, 0.3)">Избранное</h1>
            <ul class="nav type_object mb-4 pb-4" style="border-bottom: none;">
                <li value="fl" class="active gray mr-3">Квартиры</li>
                <li value="zhk" class="gray mr-3">Новостройки</li>
                <li value="parking" class="gray mr-3">Машиноместа</li>
                <li value="store" class="gray mr-3">Кладовые</li>
            </ul>
            {% if fav_fl %}
                <div class="block-1" style="display: flex; flex-wrap: wrap; clear: left;">
                {% for item in fav_fl %}
                    <div class="col-6 col-md-5 col-xl-4 res">
                        <div class="card mb-3" style="border: none;">
                            <a href="{% url 'flat_detail' item.property_pk.fk_property.city.city_slug item.property_pk.pk item.property_pk.slug %}">
                               {% if item.property_pk.fl_drawing %}
                               <img class="card-img-top py-2" src="/media/{{ item.property_pk.fl_drawing }}" alt="img" style="height: 11rem; object-fit: contain; border: 1px solid #ccc; border-radius: 0.5rem;">
                               {% else %}
                               <p class="h5" style="height: 11rem; object-fit: contain;">Изображение планировки отсутствует</p>
                               {% endif %}
                            </a>
                            <p class="heart heart-fl">
                                <span>
                                    <i id="{{ item.property_pk.id }}_fl" data-url="{{ request.path }}" class="fa fa-heart delete_fav fl" aria-hidden="true" style="color: #55B50C;"></i>
                                </span>
                            </p>
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <h6 class="card-title gray">{% if item.property_pk.fl_price %}{{ item.property_pk.fl_price|price }} &#8381;{% else %}стоимость не указана{% endif %}</h6>
                                    <p style="display: inline-block;">{% if item.property_pk.fl_decor == 'Да' %}<img src="{% static '/img/otdelka.png' %}" alt="img" title="Квартира с отделкой">
                                        {% elif item.property_pk.fl_decor == 'Нет' %}<img src="{% static '/img/net_otdelki.png' %}" alt="img" title="Квартира без отделки">
                                        {% elif item.property_pk.fl_decor == 'whitebox' %}<img src="{% static '/img/whitebox.png' %}" alt="img" title="Квартира с отделкой whitebox">
                                        {% elif item.property_pk.fl_decor == 'zak' %}<img src="{% static '/img/zak.png' %}" alt="img" title="Отделкка по желанию заказчика">{% endif %}</p>
                                </div>
                                <p class="d-flex justify-content-between gray" style="height: 1.5rem;">
                                    <span>{% if item.property_pk.fl_type == 'C' %}Студия{% else %}{{ item.property_pk.fl_type }}-х комн{% endif %}</span><span class="dot_html">&middot;</span><span>{{ item.property_pk.fl_sq }} м2</span><span class="dot_html">&middot;</span><span>{% if item.property_pk.fk_property.name == 'More (Море)' or item.property_pk.fk_property.name == 'Premium park (Премиум парк)' %}&mdash; этаж{% else %}{{ item.property_pk.floor }} этаж{% endif %}</span>
                                </p>
                                <p class="gray"><span class="font-weight-bold">{{ item.property_pk.fk_property.name }}</span> {{ item.property_pk.fk_building.num_dom }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% else %}
                <div class="block-1 heart_lk_cab">
                    <div>
                        <h4 class="mt-5 gray">Пока здесь пусто...</h4>
                        <h4 class="mt-3 mb-5 gray">Воспользуйтесь нашим <a class="a_fav" href="{% url 'sale' city='vladivostok' %}">поиском</a> и найдите, то что по душе.</h4>
                    </div>
                </div>
            {% endif %}
            <div class="block-2">
                <h4 class="mt-5 mb-5 gray">Пока здесь пусто...</h4>
            </div>
            <div class="block-4">
                <h4 class="mt-5 mb-5 gray">Пока здесь пусто...</h4>
            </div>
            {% if fav_zhk %}
                <div class="block-5" style="clear: left;">
                {% for item in fav_zhk %}
                    <div class="col-9 col-md-5 col-xl-4 res">
                        <div class="card" style="border: none">
                           <a href="{% url 'property_detail' item.property_pk.city.city_slug item.property_pk.pk item.property_pk.slug %}">
                               <img class="card-img-top" src="/media/{{ item.property_pk.buildings_set.first.small_img }}" alt="img" style="height: 10rem; border-radius: 5px">
                           </a>
                           <p class="heart">
                                <span>
                                    <i id="{{ item.property_pk.id }}_zhk" data-url="{{ request.path }}" class="fa fa-heart delete_fav zhk" aria-hidden="true" style="color: #55B50C;"></i>
                                </span>
                            </p>
                            <div class="card-body pb-0" style="position: relative; bottom: 2rem;">
                                <div class="d-flex justify-content-between">
                                    <p><span><i class="fa fa-star" aria-hidden="true" style="color: #55B50C;"></i>
                                        {% if item.property_pk.rate.first.get_rating %}{{ item.property_pk.rate.first.get_rating }}{% else %}0,0{% endif %}
                                        </span>
                                        <span class="ml-3"><i class="fa fa-comment-o" aria-hidden="true" style="color: #55B50C;"></i> {{ item.property_pk.testimonials.all|length }}</span>
                                    </p>
                                    <p class="badge badge-pill badge-success">{{ item.property_pk.buildings_set.first.get_build_stage_display }}</p>
                                </div>
                                <h4 class="card-title"><a href="{% url 'property_detail' item.property_pk.city.city_slug item.property_pk.pk item.property_pk.slug %}" style="color: #55B50C;">{{ item.property_pk.name|truncatewords:20 }}</a></h4>
                                <p class="gray mb-1">{% if item.property_pk.district %}{{ item.property_pk.district }} р-н{% else %}район не указан{% endif %}</p>
                                <p class="small gray mb-1">Срок сдачи: {{ item.property_pk.buildings_set.first.operation_term }}</p>
                                <p class="gray">Стоимость 1 м2: {% if item.property_pk.buildings_set.first.middle_price %}{{ item.property_pk.buildings_set.first.middle_price|price }} &#8381{% else %} &mdash;{% endif %}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% else %}
                <div class="block-5 heart_lk_cab">
                    <div>
                        <h4 class="mt-4 gray">Пока здесь пусто...</h4>
                        <h4 class="mt-3 mb-5 gray">Воспользуйтесь нашим <a class="a_fav" href="{% url 'property' city='vladivostok' %}">поиском</a> и найдите, то что по душе.</h4>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

cabinet/templates/cabinet/reserve.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Бронирование{% endblock title %}

{% block content %}
<div class="container px-sm-0 my-5">
    <div class="row">
        <div class="col-12 col-sm-4 col-xl-3 mb-5 left-menu">
            {% include 'cabinet/include/left-menu.html' %}
        </div>
        <div class="col-12 col-sm-8 col-xl-9 pl-sm-5">
            <h1 class="gray mb-5 pb-3" style="border-bottom: 1px solid rgba(0, 0, 0, 0.3)">Бронирование</h1>
            <ul class="nav type_object mb-4 pb-4" style="border-bottom: none;">
                <li value="fl" class="active gray mr-3">Квартиры</li>
                <li value="parking" class="gray mr-3">Машиноместа</li>
                <li value="store" class="gray mr-3">Кладовые</li>
            </ul>
            <div class="block-1">
                <h4 class="mt-5 gray">Пока здесь пусто...</h4>
                <h4 class="mt-3 mb-5 gray">Воспользуйтесь нашим <a class="a_fav" href="{% url 'sale' city='vladivostok' %}">поиском</a> и найдите, то что по душе.</h4>
            </div>
            <div class="block-2">
                <h4 class="mt-5 mb-5 gray">Пока здесь пусто...</h4>
            </div>
            <div class="block-4">
                <h4 class="mt-5 mb-5 gray">Пока здесь пусто...</h4>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

cabinet/templates/cabinet/user.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Профиль{% endblock title %}

{% block content %}
<div class="container px-sm-0 my-5">
    <div class="row">
        <div class="col-12 col-sm-4 col-xl-3 mb-5 left-menu">
            {% include 'cabinet/include/left-menu.html' %}
        </div>
        <div class="col-12 col-sm-8 col-xl-9 pl-sm-5">
            <h1 class="gray mb-5 pb-3" style="border-bottom: 1px solid rgba(0, 0, 0, 0.3)">Профиль</h1>
            <div class="profile-info d-flex flex-column">
                <div class="d-flex"><p class="col-2 px-0">Имя:</p>{{ request.user.first_name }}</div>
                <div class="d-flex"><p class="col-2 px-0">Логин на портале:</p>{{ request.user.username }}</div>
                <div class="d-flex"><p class="col-2 px-0">Почта:</p>{{ request.user.email }}</div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}