authapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from authapp import views

app_name = 'authapp'


urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.SingUpView.as_view(), name='register')
]

bashni/urls.py
from django.contrib import admin
from django.urls import path, include

import bashni.views
from bashni import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.contrib.sitemaps.views import sitemap

from main import views as main_views
from property import views as pr_views

sitemaps = {
    'index': main_views.IndexViewSitemap,
    'static': main_views.StaticViewSitemap,
    'news_slug': main_views.NewsSlugVladivostokSitemapView,
    'news': main_views.NewsSitemapView,
    'property': pr_views.PropertySitemapView,
    'property_detail': pr_views.PropertyDetailSitemapView,
    'flats_detail': pr_views.FlatsDetailSitemapView
}

handler404 = bashni.views.page_not_found_view
handler500 = bashni.views.custom_error_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('property/', include('property.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('lk/', include('cabinet.urls', namespace='cabinet')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='main'),
    path('news/', views.NewsListView.as_view(), name='news'),
    path('news/<pk>/', views.NewsDetailList.as_view(), name='news_detail'),
    path('news_slug/<tag>/', views.NewsSlugView.as_view(), name='news_slug'),
    path('loan/', views.LoanPageView.as_view(), name='loan'),
    path('repair/', views.RepairPageView.as_view(), name='repair'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('favorites/', views.FavoritesView.as_view(), name='favorites'),
    path('events/', views.EventsView.as_view(), name='events'),
    path('events/<pk>/', views.EventsDetailView.as_view(), name='events_detail'),
    path('policy/', views.PolicyView.as_view(), name='policy'),
    path('news_popular/', views.PopularNewsListView.as_view(), name='news_popular'),
    path('person_data_treatment/', views.PersonDataView.as_view(), name='person_data'),
]

property/models.py
from django.db import models
from django.contrib.auth.models import User

from PIL import Image

from ckeditor_uploader.fields import RichTextUploadingField
from slugify import slugify


def resize_image(elem):
    org_img = Image.open(elem.path)
    width, height = org_img.size
    if width > 900:
        width_ratio = round(900 / width * 100)
        org_img.save(elem.path, quality=width_ratio)


class City(models.Model):
    city_name = models.CharField(verbose_name='город', max_length=32)
    city_slug = models.SlugField(verbose_name='поле url')
    city_code = models.PositiveSmallIntegerField(verbose_name='код города')

    class Meta:
        verbose_name_plural = 'Города'

    def __str__(self):
        return self.city_name


class Facilities(models.Model):
    name = models.CharField(verbose_name='возможности', max_length=128)
    vector = models.TextField(verbose_name='вектор рисунка', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'инфраструктура ЖК'


class RatingStar(models.Model):
    value = models.PositiveSmallIntegerField(verbose_name='значение')

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name_plural = 'Звезды рейтинга' 
        ordering = ['-value']


def path_to_property(instance, filename):
    return f'property/{instance.name}/{filename}'


class Property(models.Model):
    STAGE_CHOICES = (
        ('b', 'строится'),
        ('p', 'сдан'),
        ('d', 'долгострой'),
    )
    key_words = models.CharField(max_length=256, verbose_name='ключевые слова для мета тэгов', blank=True)
    description = models.CharField(max_length=300, verbose_name='описание для мета тэгов', blank=True)
    name = models.CharField(max_length=128, verbose_name='Название ЖК', unique=True)
    slug = models.SlugField(verbose_name='поле url', max_length=128)
    build_stage = models.CharField(max_length=15, verbose_name='Стадия строительства', choices=STAGE_CHOICES, default='b')
    short_desc = RichTextUploadingField(verbose_name='Краткое описание', blank=True)
    territory_desc = RichTextUploadingField(verbose_name='Благоустройство', blank=True)
    infr_desc = RichTextUploadingField(verbose_name='Инфраструктура', blank=True)
    work_desc = RichTextUploadingField(verbose_name='Перечень работ', blank=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='Для города', related_name='prorerty')
    district = models.CharField(verbose_name='район', max_length=64, blank=True)
    buid_video = models.URLField(verbose_name='ссылка на видеонаблюдение', max_length=200, blank=True, null=True)
    gen_plan = models.ImageField(verbose_name='ген план', upload_to=path_to_property, blank=True, null=True)
    zhk_img = models.ImageField(verbose_name='картинка записаться на просмотр', upload_to=path_to_property, blank=True, null=True)
    facilities = models.ManyToManyField(Facilities, verbose_name='инфраструктура')
    video = models.URLField(verbose_name='видеопрезентация', max_length=200, blank=True, null=True,
        help_text='в конце адреса ?autoplay=1&mute=1, например: https://www.youtube.com/embed/hdi6vkQx?autoplay=1&mute=1')
    has_scraper = models.BooleanField(verbose_name='есть скрапер', default=False)
    is_active = models.BooleanField(verbose_name='активный', default=True)
    mid_rating = models.DecimalField(verbose_name='средний рейтинг новостройки', max_digits=2, decimal_places=1, default=0.0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'ЖК комплексы'
        ordering = ['name']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, ok='_', only_ascii=True)
        super(Property, self).save(*args, **kwargs)
        if self.gen_plan:
            super().save(*args, **kwargs)
            resize_image(self.gen_plan)
        if self.zhk_img:
            super().save(*args, **kwargs)
            resize_image(self.zhk_img)
       

class Rating(models.Model):
    ip = models.CharField(verbose_name='ip адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='звезда')
    property = models.ForeignKey(Property, on_delete=models.CASCADE, verbose_name='ЖК', related_name='rate')

    def get_rating(self):
        ratings = Rating.objects.filter(property=self.property)
        rate_sum = 0
        try:
            for item in ratings:
                rate_sum += item.star.value
            return round(rate_sum/len(ratings), 1)
        except Exception:
            return 0.0

    class Meta:
        verbose_name_plural = 'Рейтинг'


class PropertyTestimonials(models.Model):
    date = models.DateField(verbose_name='дата публикации', auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    testimonial = models.TextField(verbose_name='отзыв', max_length=512)
    fk_property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='testimonials')

    def __str__(self):
        return f'{self.date} {self.testimonial}'

    class Meta:
        verbose_name_plural = 'Отзывы о ЖК'


def img_path_small(instance, filename):
    return f'property/{instance.get_build_stage_display()}/{instance.id}/{filename}'


class Buildings(models.Model):
    STAGE_CHOICES = (
        ('b', 'строится'),
        ('p', 'сдан'),
        ('d', 'долгострой'),
    )
    key_words = models.CharField(max_length=256, verbose_name='ключевые слова для мета тэгов', blank=True)
    description = models.CharField(max_length=300, verbose_name='описание для мета тэгов', blank=True)
    fk_property = models.ForeignKey(Property, on_delete=models.CASCADE, verbose_name='ЖК')
    num_dom = models.CharField(max_length=64, verbose_name='номер строения/название дома')
    start_date = models.PositiveIntegerField(verbose_name='год начала строительства', blank=True, null=True)
    build_stage = models.CharField(max_length=15, verbose_name='Стадия строительства', choices=STAGE_CHOICES, default='b')
    addr = models.CharField(max_length=256, verbose_name='Адрес')
    small_img = models.ImageField(upload_to=img_path_small, verbose_name='уменьшенное фото')
    main_contractor = models.CharField(max_length=64, verbose_name='Застройщик')
    building_company = models.CharField(max_length=128, verbose_name='Подрядчик', blank=True)
    pr_declaration = models.CharField(max_length=128, verbose_name='Проектная декларация')
    pr_decl_link = models.URLField(verbose_name='Ссылка на проектную декларацию')
    operation_term = models.CharField(max_length=32, verbose_name='Ввод в эксплуатацию')
    send_keys = models.DateField(verbose_name='Выдача ключей', blank=True, null=True)
    middle_price = models.PositiveIntegerField(verbose_name='Средняя цена за 1 м2', blank=True, null=True)
    property_class = models.CharField(max_length=32, verbose_name='Класс недвижимости')
    wall = models.CharField(max_length=32, verbose_name='Материал стен')
    decoration = models.CharField(max_length=32, verbose_name='Тип отделки')
    free_planning = models.CharField(max_length=20, verbose_name='Свободная планировка')
    floors = models.PositiveSmallIntegerField(verbose_name='Количество этажей')
    q_flats = models.PositiveSmallIntegerField(verbose_name='Количество квартир')
    living_sq = models.PositiveIntegerField(verbose_name='Жилая площадь')
    ceil_height = models.CharField(max_length=15, verbose_name='Высота потолков')
    sales_flats = models.CharField(verbose_name='распроданность квартир', max_length=32, blank=True)
    sales_not_living = models.CharField(verbose_name='распроданность нежилых помещений', max_length=32, blank=True)
    sales_parking = models.CharField(verbose_name='распроданность машиномест', max_length=32, blank=True)
    is_active = models.BooleanField(verbose_name='активный', default=True)

    class Meta:
        verbose_name_plural = 'Объекты недвижимости'
        ordering = ['middle_price', 'operation_term', 'num_dom']

    def __str__(self):
        return self.num_dom


def img_path_photo(instance, filename):
    return f'property/{instance.fk_building.get_build_stage_display()}/{instance.fk_building.id}/{filename}'


class MainPhotos(models.Model):
    main_img = models.ImageField(upload_to=img_path_photo, verbose_name='фото')
    fk_building = models.ForeignKey(Buildings, on_delete=models.CASCADE, verbose_name='для объекта',
                                    related_name='main_photos')

    class Meta:
        verbose_name_plural = 'Основные фото'


def img_path_build(instance, filename):
    return f'property/{instance.fk_month.fk_building.get_build_stage_display()}/{instance.fk_month.fk_building.id}/building/{instance.fk_month.build_month}/{filename}'


class BuildMonths(models.Model):
    build_month = models.CharField(max_length=20, verbose_name='Месяц строительства')
    fk_building = models.ForeignKey(Buildings, on_delete=models.CASCADE, verbose_name='для объекта',
                                    related_name='build_months')
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        verbose_name_plural = 'Фото объектов по месяцам стр-ва'


class BuildingPhotos(models.Model):
    build_img = models.ImageField(upload_to=img_path_build, blank=True, null=True)
    fk_month = models.ForeignKey(BuildMonths, on_delete=models.CASCADE, verbose_name='месяц',
                                 related_name='build_photos')

    class Meta:
        verbose_name_plural = 'Фото строительства'


class ObjectDocuments(models.Model):
    doc_name = models.CharField(max_length=128, verbose_name='Тип документа')
    doc_date = models.DateTimeField(verbose_name='Дата размещения')
    doc_link = models.URLField(verbose_name='ссылка на документ')
    fk_object = models.ForeignKey(Buildings, on_delete=models.CASCADE, related_name='documents', verbose_name='для объекта')

    def __str__(self):
        return self.doc_name

    class Meta:

main/forms.py
from django import forms

from main.models import NewsComment


class NewsCommentForm(forms.ModelForm):
    class Meta:
        model = NewsComment
        fields = ['comment_text']

    def __init__(self, *args, **kwargs):
        super(NewsCommentForm, self).__init__(*args, **kwargs)
        self.fields['comment_text'] = forms.CharField(max_length=512, label='текст комментария',
                                                      widget=forms.Textarea(attrs={'rows': 5}), required=False)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %} {{ title|title }} {% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400;1,500;1,600&family=Ubuntu:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/css/bootstrap-slider.min.css">
	<link rel="stylesheet" href="{% static 'css/chief-slider.css' %}">
</head>
<body>
	<header>
		<div class="modal fade" id="searchModal" tabindex="-1" role="dialog">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						<form action="{% url 'search' %}" method="get">
							<input class="form-control" type="text" name="q" placeholder="введите запрос...">
							<button class="btn btn-primary px-5 mt-3" type="submit">поиск</button>
						</form>
					</div>
				</div>
			</div>
		</div>
		<nav class="navbar navbar-expand-md navbar-light">
		  <div class="container-fluid">
		    <a class="navbar-brand pt-0" href="{% url 'main' %}"><img src="{% static 'img/new_logo.png' %}" alt="logo"></a>
			<button class="navbar-toggler mt-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav mx-auto">
				<li class="nav-item px-md-3"><a href="{% url 'news' %}" class="nav-link {% if request.resolver_match.url_name == 'news' %}active{% endif %}">Новости</a></li>
			    <!--li class="nav-item px-md-3"><a href="{% url 'loan' %}" class="nav-link {% if request.resolver_match.url_name == 'loan' %}active{% endif %}">Ипотека</a></li-->
			    <li class="nav-item px-md-3"><a href="{% url 'property' city='vladivostok' %}" class="nav-link {% if request.resolver_match.url_name == 'property' %}active{% endif %}">Новостройки</a></li>
			    <li class="nav-item px-md-3"><a href="{% url 'sale' city='vladivostok' %}" class="nav-link {% if request.resolver_match.url_name == 'sale' %}active{% endif %}">Квартиры</a></li>
			    <!--li class="nav-item px-md-3"><a href="{% url 'repair' %}" class="nav-link {% if request.resolver_match.url_name == 'repair' %}active{% endif %}">Ремонт</a></li-->
			  </ul>
			</div>
		    <div class="user">
			  <ul class="nav ml-auto d-sm-flex flex-row align-items-center">
			  	<li class="nav-item py-3 pr-3 pr-sm-0"><a href="{% if request.user.is_authenticated %}{% url 'cabinet:main' request.user.pk %}{% else %}{% url 'favorites' %}{% endif %}"><img src="{% static 'img/fav_icon.png' %}" alt="favorite_icon"></a></li>
				<li class="nav-item py-3 pl-sm-3"><a data-toggle="modal" data-target="#searchModal" href="#"><img src="{% static 'img/search_icon.png' %}" alt="#"></a></li>
				<li class="nav-item dropdown py-2">
					<a class="nav-link dropdown-toggle pr-0" href="" id="navbarDropdown" role="button" data-toggle="dropdown">
						{% if user.is_authenticated %}<img src="{% static 'img/user_logged_icon.png' %}" alt="#">{% else %}
						<img src="{% static 'img/user_icon.png' %}" alt="#">{% endif %}
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						{% if user.is_authenticated %}
							<a href="{% url 'cabinet:main' request.user.pk %}" class="dropdown-item">Личный кабинет</a>
							<a href="{% url 'authapp:logout' %}" class="dropdown-item">Выход</a>
						{% else %}
							<a href="{% url 'authapp:login' %}?next={{ request.path }}" class="dropdown-item">Войти</a>
							<a href="{% url 'authapp:register' %}" class="dropdown-item">Регистрация</a>
						{% endif %}
					</div>
				</li>
				<li class="navbar item pr-0"><img src="{% static 'img/phone_icon.png' %}" alt="#"></li>
				<li class="navbar item pl-0 ph"><a class="nav-link" href="tel:+74232800270" style="color: black;">
					+7(423)280-02-07</a></li>
			  </ul>
		    </div>
		  </div>
		</nav>
	<div class="border-div"></div>
	</header>

	{% block content %}

    {% endblock %}
	<footer>
		<div class="container-fluid" style="border-top: 1px solid #8D8D8D;">
			<div class="row mt-3">
				<div class="col-12 navbar d-flex-justify-content-around">
					<a class="navbar-brand nav_foot ml-5" href="{% url 'main' %}"><img src="{% static 'img/new_logo.png' %}" alt="logo"></a>
					<ul class="nav mx-auto nav-footer">
						<li class="nav-item px-md-3"><a href="{% url 'news' %}" class="nav-link {% if request.resolver_match.url_name == 'news' %}active{% endif %}">Новости</a></li>
						<!--li class="nav-item px-md-3"><a href="{% url 'loan' %}" class="nav-link {% if request.resolver_match.url_name == 'loan' %}active{% endif %}">Ипотека</a></li-->
						<li class="nav-item px-md-3"><a href="{% url 'property' city='vladivostok' %}" class="nav-link {% if request.resolver_match.url_name == 'property' %}active{% endif %}">Новостройки</a></li>
						<li class="nav-item px-md-3"><a href="{% url 'sale' city='vladivostok' %}" class="nav-link {% if request.resolver_match.url_name == 'sale' %}active{% endif %}">Квартиры</a></li>
						<!--li class="nav-item px-md-3"><a href="{% url 'repair' %}" class="nav-link {% if request.resolver_match.url_name == 'repair' %}active{% endif %}">Ремонт</a></li-->
					</ul>
					<div class="phn-footer text-center h2 align-self-center mt-3"><a class="gray" href="phone:+74232800207">+7(423)280-02-07</a></div>
				</div>
			</div>
			<div class="row first-row-footer mt-3 mb-5 justify-content-between">
				<div class="col-md-4 text-center h2 align-self-center mb-0 phone-footer"><a href="phone:+74232800207">+7(423)280-02-07</a></div>
				<div class="col-6 col-md-4 text-center h2 align-self-center mb-0"><a href="mailto:info@111bashni.ru">info@111bashni.ru</a></div>
				<div class="col-6 col-md-4 text-center">
					<a href="https://t.me/bashni111"><img class="img-footer" src="{% static 'img/telegram_icon.png' %}" alt="icon" style="position: '';"></a>
					<a href="https://vk.com/bashni111"><img class="img-footer" src="{% static 'img/vk_icon.png' %}" alt="icon"></a>
					<a href="https://www.youtube.com/channel/UCJn9mSFd5v-EOqV2NJ1_Mkg?view_as=subscriber"><img class="img-footer" src="{% static 'img/youtube_icon.png' %}" alt="icon"></a>
				</div>
			</div>
			<div class="row second-row-footer mb-3 justify-content-center">
				<div class="col-6 col-sm-4 mail">
					<p><a href="">О сайте</a></p>
					<p><a href="">Вакансии</a></p>
					<p><a href="">Наши партнеры</a></p>
					<p><a href="">Правила пользования сайтом</a></p>
					<p><a href="{% url 'policy' %}">Политика конфиденциальности</a></p>
					<h5 class="my-2"><a href="">Справочник дольщика</a></h5>
					<p><a href="">Форум новостроек</a></p>
					<p><a href="">Юридическая поддержка</a></p>
				</div>
				<div class="col-6 col-sm-4">
					<h5 class="mb-2"><a href="">Жилые комплексы новостройки Владивостока</a></h5>
					<p><a href="">Новостройки на карте</a></p>
					<p><a href="">Сданные новостройки</a><span class="px-2" style="color: #bababa;">|</span><a href="{% url 'property' city='vladivostok' %}">Строящиеся</a></p>
					<p><a href="{% url 'property' city='vladivostok' %}">Новостройки</a><span class="px-2" style="color: #bababa;">|</span><a href="">Долгострои</a></p>
					<p><a href="{% url 'property' city='vladivostok' %}?b_class=%D0%9A%D0%BE%D0%BC%D1%84%D0%BE%D1%80%D1%82&decor=&wall=">Типовой</a>
						<span class="px-2" style="color: #bababa;">|</span>
						<a href="{% url 'property' city='vladivostok' %}?b_class=%D0%9A%D0%BE%D0%BC%D1%84%D0%BE%D1%80%D1%82&decor=&wall=">Комфорт</a>
						<span class="px-2" style="color: #bababa;">|</span>
						<a href="{% url 'property' city='vladivostok' %}?b_class=%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81&decor=&wall=">Бизнес</a></p>
					<p><a href="{% url 'sale' city='vladivostok' %}">Купить квартиру в новостройке</a></p>
					<p><a href="{% url 'sale' city='vladivostok' %}?flat_type=C&fl_decor=">Квартиры-студии</a></p>
					<p><a href="{% url 'sale' city='vladivostok' %}?flat_type=1&fl_decor=">1-комнатные квартиры</a></p>
					<p><a href="{% url 'sale' city='vladivostok' %}?flat_type=2&fl_decor=">2-комнатные квартиры</a></p>
					<p><a href="{% url 'sale' city='vladivostok' %}?flat_type=3&fl_decor=">3-комнатные квартиры</a></p>
					<p><a href="">Пентхаусы</a></p>
					<p><a href="">Коммерческая недвижимость</a></p>
					<h5 class="my-2"><a href="">Застройщики Владивостока</a></h5>
					<p><a href="">Обмен на новостройку</a></p>
					<p><a href="">Ипотека в новостройке</a></p>
					<p><a href="">Ремонт в новостройке</a></p>
				</div>
				<div class="col-6 col-sm-4">
					<h5 class="mb-2"><a href="">Рейтинг новостроек жилых комплексов</a></h5>
					<ul>
						<li><a href="{% url 'property_detail' city_slug='vladivostok' pk=328 slug='aivazovskii' %}">ЖК Айвазовский (Владивосток)</a></li>
						<li><a href="">ЖК Академгородок (Владивосток)</a></li>
						<li><a href="{% url 'property_detail' city_slug='vladivostok' pk=365 slug='dolina' %}">ЖК Золотая долина (Владивосток)</a></li>
						<li><a href="">ЖК Ласточка (Владивосток)</a></li>
						<li><a href="">ЖК Ольга (Владивосток)</a></li>
						<li><a href="{% url 'property_detail' city_slug='vladivostok' pk=373 slug='sadovyi_kvartal' %}">ЖК Садовый квартал (Владивосток)</a></li>
						<li><a href="{% url 'property_detail' city_slug='vladivostok' pk=289 slug='chaika' %}">ЖК Чайка (Владивосток)</a></li>
						<li><a href="{% url 'property_detail' city_slug='vladivostok' pk=403 slug='eco_siti' %}">ЖК Экосити (Владивосток)</a></li>
					</ul>
				</div>
			</div>
			<div class="row second-row-footer mb-3">
				<div class="col-12">
					<p class="mt-5" style="color: #6F6868; margin-left: 6rem;">&copyООО «Башни», 2020-2022</p>
					<p style="color: #6F6868; margin-left: 6rem;">Копирование информации сайта допускается только при условии указания Гиперссылки на источник информации.</p>
					<p style="color: #6F6868; margin-left: 6rem;">Любая информация, представленная на данном сайте, носит исключительно информационный характер и ни при каких
					условиях не является публичной офертой, определяемой положениями статьи 437 ГК РФ.</p>
				</div>
			</div>
		</div>
	</footer>
	{% block js %}
	<script src="{% static 'js/jquery-3.6.0-min.js' %}"></script>
	<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
	<!--script src="https://use.fontawesome.com/aeedf3f379.js"></script-->
	<script src="https://kit.fontawesome.com/9fc41faa36.js" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/bootstrap-slider.min.js"></script>
	<script src="{% static 'js/script.js' %}"></script>
	{% endblock %}
</body>
</html>

main/templates/main/in_development_mode.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Страница в разработке{% endblock title %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <h5 class="my-5 font-italic" style="color: #1A284C;">Данный раздел находится в разработке и в скором времени
            здесь появится актуальный контент.
        </h5>
    </div>
</div>
{% endblock content %}

main/templates/main/person_data.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Обработка персональных данных{% endblock title %}

{% block content %}
<div class="container my-5">
  <div class="row">
    <div class="col-12">
      <h1 class="text-center gray mb-5">Согласие на сбор и обработку персональных данных</h1>
      <div class="gray" style="text-align: justify">{{ object.text_field|safe }}</div>
    </div>
  </div>
</div>
{% endblock content %}